export default {
  "code": 1,
  "message": "Success",
  "data": {
    "defaultServices": [{
        "id": 1054,
        "spuName": "在线管家服务",
        "name": "含摄像头",
        "imageUrl": "",
        "price": 199900,
        "quantity": 1,
        "categoryTypeId": 8,
        "serviceName": "设计服务",
        "serviceType": 1,
        "storeId": 0
      },
      {
        "id": 38085,
        "spuName": "韩永辉测试视频无法播放",
        "name": "橙色",
        "imageUrl": "https://ali-image-test.dabanjia.com//image/20210313/1615618135579_0296%24pexels-eberhard-grossgasteiger-1428277.jpg",
        "price": 1,
        "quantity": 1,
        "categoryTypeId": 6,
        "serviceName": "设计服务",
        "serviceType": 1,
        "storeId": 2
      }
    ],
    "purchasedServiceList": [{
        "nodeName": "设计", //"string //节点名称:设计 精算 管家 拆除 水电 泥工 木工 油漆",
        "serveRole": 1, //"int //服务者角色:1 23 17 14 14 14 14 14",
        "serveWorkType": -1, //"int //服务者工种:-1 -1 -1 5 6 2 1 3",
        "nodeStatus": 2, //"int //节点状态 1:未开始 2:进行中 3:已完成 4:已跳过",
        "nextNodeId": 1, //"long //后驱节点id",
        "serveName": "王斌彦", //"string //服务者姓名",
        "payStatus": 0, //"int //工序支付状态 0:未支付 1:部分支付 2:全部支付",
        "processNumerator": 1, //"int //节点进度（分子值）",
        "processDenominator": 2, //"int //节点进度（分母值）",
        "nodeType": 1, //"int //节点类型 1:设计 2:验房 3:量房 4:精算 5:管家 6:拆除 7:水电 8:泥工 9:木工 10:油漆",
        "serviceName": "设计", //"string //服务名称",
        "status": 0, //"int //状态 0未开始 1已取消 2进行中 3休眠中 4待确认 5已完成 6原始结构图待验收 7原始结构图待验收 8已完成 9已完成 10上门时间待确认\r      @see com.dabanjia.witch.doctor.pm.constants.ServeCardStatusEnum",
        "statusName": "进行中", // "string //状态 0未开始 1已取消 2进行中 3休眠中 4待确认 5已完成\r      @see com.dabanjia.witch.doctor.pm.constants.ServeCardStatusEnum",
        "commentStatus": 0, // "int //评价状态 0未评价 1已评价",
        "grepOrderStatus": 1, // "int //当服务卡状态为未开始时，判断抢单状态\r      抢单状态 0抢单中 1待业主确认 2待重新派单 3已确认\r      @see com.dabanjia.witch.doctor.pm.constants.SnatchOrderStatusEnum",
        "grepOrderStatusName": "待业主确认", // "string //抢单状态 名称"
      },
      {
        "nodeName": "精算", //"string //节点名称:设计 精算 管家 拆除 水电 泥工 木工 油漆",
        "serveRole": 1, //"int //服务者角色:1 23 17 14 14 14 14 14",
        "serveWorkType": -1, //"int //服务者工种:-1 -1 -1 5 6 2 1 3",
        "nodeStatus": 2, //"int //节点状态 1:未开始 2:进行中 3:已完成 4:已跳过",
        "nextNodeId": 1, //"long //后驱节点id",
        "serveName": "王斌彦", //"string //服务者姓名",
        "payStatus": 0, //"int //工序支付状态 0:未支付 1:部分支付 2:全部支付",
        "processNumerator": 1, //"int //节点进度（分子值）",
        "processDenominator": 2, //"int //节点进度（分母值）",
        "nodeType": 1, //"int //节点类型 1:设计 2:验房 3:量房 4:精算 5:管家 6:拆除 7:水电 8:泥工 9:木工 10:油漆",
        "serviceName": "设计", //"string //服务名称",
        "status": 2, //"int //状态 0未开始 1已取消 2进行中 3休眠中 4待确认 5已完成 6原始结构图待验收 7原始结构图待验收 8已完成 9已完成 10上门时间待确认\r      @see com.dabanjia.witch.doctor.pm.constants.ServeCardStatusEnum",
        "statusName": "进行中", // "string //状态 0未开始 1已取消 2进行中 3休眠中 4待确认 5已完成\r      @see com.dabanjia.witch.doctor.pm.constants.ServeCardStatusEnum",
        "commentStatus": 0, // "int //评价状态 0未评价 1已评价",
        "grepOrderStatus": 3, // "int //当服务卡状态为未开始时，判断抢单状态\r      抢单状态 0抢单中 1待业主确认 2待重新派单 3已确认\r      @see com.dabanjia.witch.doctor.pm.constants.SnatchOrderStatusEnum",
        "grepOrderStatusName": "业主已确认", // "string //抢单状态 名称"
      },
      {
        "nodeName": "管家", //"string //节点名称:设计 精算 管家 拆除 水电 泥工 木工 油漆",
        "serveRole": 1, //"int //服务者角色:1 23 17 14 14 14 14 14",
        "serveWorkType": -1, //"int //服务者工种:-1 -1 -1 5 6 2 1 3",
        "nodeStatus": 2, //"int //节点状态 1:未开始 2:进行中 3:已完成 4:已跳过",
        "nextNodeId": 1, //"long //后驱节点id",
        "serveName": "王斌彦", //"string //服务者姓名",
        "payStatus": 0, //"int //工序支付状态 0:未支付 1:部分支付 2:全部支付",
        "processNumerator": 1, //"int //节点进度（分子值）",
        "processDenominator": 2, //"int //节点进度（分母值）",
        "nodeType": 1, //"int //节点类型 1:设计 2:验房 3:量房 4:精算 5:管家 6:拆除 7:水电 8:泥工 9:木工 10:油漆",
        "serviceName": "设计", //"string //服务名称",
        "status": 2, //"int //状态 0未开始 1已取消 2进行中 3休眠中 4待确认 5已完成 6原始结构图待验收 7原始结构图待验收 8已完成 9已完成 10上门时间待确认\r      @see com.dabanjia.witch.doctor.pm.constants.ServeCardStatusEnum",
        "statusName": "进行中", // "string //状态 0未开始 1已取消 2进行中 3休眠中 4待确认 5已完成\r      @see com.dabanjia.witch.doctor.pm.constants.ServeCardStatusEnum",
        "commentStatus": 0, // "int //评价状态 0未评价 1已评价",
        "grepOrderStatus": 3, // "int //当服务卡状态为未开始时，判断抢单状态\r      抢单状态 0抢单中 1待业主确认 2待重新派单 3已确认\r      @see com.dabanjia.witch.doctor.pm.constants.SnatchOrderStatusEnum",
        "grepOrderStatusName": "业主已确认", // "string //抢单状态 名称"
      },
      {
        "nodeName": "拆除", //"string //节点名称:设计 精算 管家 拆除 水电 泥工 木工 油漆",
        "serveRole": 1, //"int //服务者角色:1 23 17 14 14 14 14 14",
        "serveWorkType": -1, //"int //服务者工种:-1 -1 -1 5 6 2 1 3",
        "nodeStatus": 2, //"int //节点状态 1:未开始 2:进行中 3:已完成 4:已跳过",
        "nextNodeId": 1, //"long //后驱节点id",
        "serveName": "王斌彦", //"string //服务者姓名",
        "payStatus": 0, //"int //工序支付状态 0:未支付 1:部分支付 2:全部支付",
        "processNumerator": 1, //"int //节点进度（分子值）",
        "processDenominator": 2, //"int //节点进度（分母值）",
        "nodeType": 1, //"int //节点类型 1:设计 2:验房 3:量房 4:精算 5:管家 6:拆除 7:水电 8:泥工 9:木工 10:油漆",
        "serviceName": "设计", //"string //服务名称",
        "status": 2, //"int //状态 0未开始 1已取消 2进行中 3休眠中 4待确认 5已完成 6原始结构图待验收 7原始结构图待验收 8已完成 9已完成 10上门时间待确认\r      @see com.dabanjia.witch.doctor.pm.constants.ServeCardStatusEnum",
        "statusName": "进行中", // "string //状态 0未开始 1已取消 2进行中 3休眠中 4待确认 5已完成\r      @see com.dabanjia.witch.doctor.pm.constants.ServeCardStatusEnum",
        "commentStatus": 0, // "int //评价状态 0未评价 1已评价",
        "grepOrderStatus": 3, // "int //当服务卡状态为未开始时，判断抢单状态\r      抢单状态 0抢单中 1待业主确认 2待重新派单 3已确认\r      @see com.dabanjia.witch.doctor.pm.constants.SnatchOrderStatusEnum",
        "grepOrderStatusName": "业主已确认", // "string //抢单状态 名称"
      }
    ],
    "availableServiceList": [{
      "nodeName": "精算", //"string //节点名称:设计 精算 管家 拆除 水电 泥工 木工 油漆",
      "serveRole": 1, //"int //服务者角色:1 23 17 14 14 14 14 14",
      "serveWorkType": -1, //"int //服务者工种:-1 -1 -1 5 6 2 1 3",
      "nodeStatus": 2, //"int //节点状态 1:未开始 2:进行中 3:已完成 4:已跳过",
      "nextNodeId": 1, //"long //后驱节点id",
      "serveName": "王斌彦", //"string //服务者姓名",
      "payStatus": 0, //"int //工序支付状态 0:未支付 1:部分支付 2:全部支付",
      "processNumerator": 1, //"int //节点进度（分子值）",
      "processDenominator": 2, //"int //节点进度（分母值）",
      "nodeType": 1, //"int //节点类型 1:设计 2:验房 3:量房 4:精算 5:管家 6:拆除 7:水电 8:泥工 9:木工 10:油漆",
      "serviceName": "设计", //"string //服务名称",
      "status": 2, //"int //状态 0未开始 1已取消 2进行中 3休眠中 4待确认 5已完成 6原始结构图待验收 7原始结构图待验收 8已完成 9已完成 10上门时间待确认\r      @see com.dabanjia.witch.doctor.pm.constants.ServeCardStatusEnum",
      "statusName": "进行中", // "string //状态 0未开始 1已取消 2进行中 3休眠中 4待确认 5已完成\r      @see com.dabanjia.witch.doctor.pm.constants.ServeCardStatusEnum",
      "commentStatus": 0, // "int //评价状态 0未评价 1已评价",
      "grepOrderStatus": 3, // "int //当服务卡状态为未开始时，判断抢单状态\r      抢单状态 0抢单中 1待业主确认 2待重新派单 3已确认\r      @see com.dabanjia.witch.doctor.pm.constants.SnatchOrderStatusEnum",
      "grepOrderStatusName": "业主已确认", // "string //抢单状态 名称"
    }],
    "insuranceStatus": 0, // "int //工地保险状态（0:未购买, 1:已购买）",
    "showDesignFlag": true, // "boolean //是否展示设计图",
    "showActuaryFlag": true, // "boolean //精算单",
    "showVideoFlag": true, // "boolean //工地视频",
    "constructionFlag": true, // "boolean //施工按钮"
  }
}
