apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mp-h5-${PROFILE}
  name: mp-h5-${PROFILE}
  namespace: witch-doctor-${PROFILE}
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mp-h5-${PROFILE}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mp-h5-${PROFILE}
    spec:
      containers:
        - image: ${ORIGIN_REPO}/${REPO}-${PROFILE}:${IMAGE_TAG}_FE
          imagePullPolicy: Always
          name: mp-h5-${PROFILE}
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          resources:
            requests:
              cpu: '0.5'
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: k8s-dabanjia-image
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      nodeSelector:
        env: release
