export const emojiMap = {
  "[拜托]":"https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_baituo.png",
  "[抱抱]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_baobao.png",
  "[抱拳]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_baoquan.png",
  "[柴柴]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_chaichai.png",
  "[吃惊]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_chijing.png",
  "[得意]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_deyi.png",
  "[尴尬]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_ganga.png",
  "[害羞]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_haixiu.png",
  "[汗]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_han.png",
  "[好的]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_haode.png",
  "[哼]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_heng.png",
  "[花花]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_huahua.png",
  "[加油]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_jiayou.png",
  "[咖啡]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_kafei.png",
  "[开心]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_kaixin.png",
  "[可怜]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_kelian.png",
  "[么么]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_meme.png",
  "[没问题]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_meiwenti.png",
  "[难过]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_nanguo.png",
  "[破涕为笑]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_potiweixiao.png",
  "[强]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_qiang.png",
  "[亲亲]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_qinqin.png",
  "[伤心]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_shangxin.png",
  "[胜利]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_shengli.png",
  "[偷笑]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_touxiao.png",
  "[晚安]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_wanan.png",
  "[微笑]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_weixiao.png",
  "[握手]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_woshou.png",
  "[捂脸]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_wulian.png",
  "[愉快]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_yukuai.png",
  "[郁闷]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_yumen.png",
  "[抓狂]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_zhuakuang.png",
  "[OK]": "https://ali-image.dabanjia.com/static/mp/dabanjia/emojis/emoji_OK.png"
}
export const emojiName = [
  "[微笑]",
  "[得意]",
  "[愉快]",
  "[害羞]",
  "[好的]",
  "[汗]",
  "[可怜]",
  "[抓狂]",
  "[难过]",
  "[吃惊]",
  "[破涕为笑]",
  "[抱拳]",
  "[伤心]",
  "[郁闷]",
  "[捂脸]",
  "[开心]",
  "[柴柴]",
  "[偷笑]",
  "[没问题]",
  "[花花]",
  "[咖啡]",
  "[抱抱]",
  "[晚安]",
  "[尴尬]",
  "[拜托]",
  "[加油]",
  "[OK]",
  "[强]",
  "[胜利]",
  "[握手]",
  "[亲亲]",
  "[么么]",
  "[哼]",
]
